# Simple workflow for deploying static content to GitHub Pages
name: Upload README to WIKI.js

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    environment: dev #Selection of the Environment
    steps:
      # Check Out the README file to workspace
      - name: Checkout README file
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            README.md
          sparse-checkout-cone-mode: true

      # Upload to Wiki
      - name: Upload README.md to Wiki.js
        env:
          WIKI_API_TOKEN: ${{ secrets.WIKI_API_TOKEN }}
          WIKI_API_URL: ${{ vars.WIKI_API_URL }}
          WIKI_PAGE_ID: ${{ vars.WIKI_PAGE_ID }}
        run: |
          CONTENT=$(cat README.md | jq -Rs .)
          curl -X POST $WIKI_API_URL \
            -H "Authorization: Bearer $WIKI_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "query": "mutation UpdatePage($id: Int!, $content: String!) { pages { update(id: $id, content: $content, description: \"README atualizado\", editor: \"markdown\", isPrivate: false, isPublished: true, locale: \"en\", path: \"Pedro/nova-pagina\", tags: [\"updated\"]) { responseResult { succeeded slug message } } } }",
              "variables": {
                "id": 24,
                "content": '"$CONTENT"'
              }
            }'

